routes/web.php
Route::get('/editing-request', [App\Http\Controllers\EditController::class, 'index'])->name('editReq');
Route::get('/create/editing-request/{id}', [App\Http\Controllers\EditController::class, 'create'])->name('createeditReq');
Route::post('/store/editing-request/{id}', [App\Http\Controllers\EditController::class, 'store'])->name('storeeditReq');
Route::pUT('/update/editing-request/{id}', [App\Http\Controllers\EditController::class, 'update'])->name('updateeditReq');
Route::get('/accept/editing-request/{id}', [App\Http\Controllers\EditController::class, 'accept'])->name('accept');
Route::get('/decline/editing-request/{id}', [App\Http\Controllers\EditController::class, 'decline'])->name('decline');
Route::get('/hold/editing-request/{id}', [App\Http\Controllers\EditController::class, 'hold'])->name('hold');
Route::get('/waiting/editing-request/{id}', [App\Http\Controllers\EditController::class, 'waiting'])->name('waiting');
Route::get('/trouble/editing-request/{id}', [App\Http\Controllers\EditController::class, 'trouble'])->name('trouble');
Route::get('/finish/editing-request/{id}', [App\Http\Controllers\EditController::class, 'finish'])->name('finish');
Route::get('/delete/request-editing/{id}', [App\Http\Controllers\EditController::class, 'delete'])->name('hapus');
Route::get('/edit/request-editing/{id}', [App\Http\Controllers\EditController::class, 'edit'])->name('edit');
Route::get('/export/Editingrequest', [App\Http\Controllers\EditController::class, 'export'])->name('exportEditingrequest');
Route::get('/reset/Editingrequest', [App\Http\Controllers\EditController::class, 'reset'])->name('resetEditingrequest');

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//Profil Controller
Route::post('/edit/foto-profil', [App\Http\Controllers\ProfilController::class, 'addImage'])->name('editFP');
Route::post('/change-password', [App\Http\Controllers\ProfilController::class, 'chgPwd'])->name('ubahPwd');
Route::get('/delete/user/{id}', [App\Http\Controllers\ProfilController::class, 'delete'])->name('hapus');

//ae live
Route::get('/AELive/Management', [App\Http\Controllers\AeLiveController::class, 'management'])->name('management.ae-live');
 Route::get('/AELive', [App\Http\Controllers\AeLiveController::class, 'show'])->name('ae-live');
 Route::get('/add/AELive', [App\Http\Controllers\AeLiveController::class, 'create'])->name('add.ae-live');
 Route::post('/store/AELive', [App\Http\Controllers\AeLiveController::class, 'store'])->name('store.ae-live');
 Route::get('/edit/AELive/{id}', [App\Http\Controllers\AeLiveController::class, 'edit'])->name('edit.ae-live');
 Route::put('/update/AELive/{id}', [App\Http\Controllers\AeLiveController::class, 'update'])->name('update.ae-live');
 Route::get('/delete/AELive/{id}', [App\Http\Controllers\AeLiveController::class, 'destroy'])->name('delete.ae-live');

//admin
Route::namespace('App\Http\Controllers')->name('admin.')->middleware([])->prefix('admin')->group(function () {
    Route::get('/show/allUsers', [App\Http\Controllers\ProfilController::class, 'showUser'])->name('users');
    Route::get('/allUsers', [App\Http\Controllers\ProfilController::class, 'indexUser'])->name('oke');
    Route::get('/change-role-user/{id}/{level}', [App\Http\Controllers\ProfilController::class, 'chgRoleUser'])->name('chgRole');
    
    //poster 
    Route::get('/poster', [App\Http\Controllers\PosterInfoController::class, 'index'])->name('poster');
    Route::post('/store/poster', [App\Http\Controllers\PosterInfoController::class, 'store'])->name('store.poster');
    Route::put('/update/poster/{id}', [App\Http\Controllers\PosterInfoController::class, 'update'])->name('update.poster');
    Route::get('/delete/poster/{id}', [App\Http\Controllers\PosterInfoController::class, 'destroy'])->name('delete.poster');

    //digital documents 
    Route::get('/digital-documents/{kategori}', [App\Http\Controllers\DigitalDocumentsController::class, 'index'])->name('digital_documents');
    Route::post('/store/digital_documents', [App\Http\Controllers\DigitalDocumentsController::class, 'store'])->name('store.digital_documents');
    Route::put('/update/digital_documents/{id}', [App\Http\Controllers\DigitalDocumentsController::class, 'update'])->name('update.digital_documents');
    Route::get('/delete/digital_documents/{id}', [App\Http\Controllers\DigitalDocumentsController::class, 'destroy'])->name('delete.digital_documents');

    //property inv
    Route::get('/propertyinv', [App\Http\Controllers\PropertyinvController::class, 'index'])->name('property-inv');
    Route::get('/add/propertyinv', [App\Http\Controllers\PropertyinvController::class, 'create'])->name('add.property-inv');
    Route::post('/store/propertyinv', [App\Http\Controllers\PropertyinvController::class, 'store'])->name('store.property-inv');
    Route::get('/edit/propertyinv/{id}', [App\Http\Controllers\PropertyinvController::class, 'edit'])->name('edit.property-inv');
    Route::put('/update/propertyinv/{id}', [App\Http\Controllers\PropertyinvController::class, 'update'])->name('update.property-inv');
    Route::get('/delete/propertyinv/{id}', [App\Http\Controllers\PropertyinvController::class, 'delete'])->name('delete.property-inv');

    //purchasing req
    Route::get('/reset', [App\Http\Controllers\PurchasingreqController::class, 'reset']);
    Route::get('/purchasing-req', [App\Http\Controllers\PurchasingreqController::class, 'index'])->name('purchasing-req');
    Route::get('/add/purchasing-req', [App\Http\Controllers\PurchasingreqController::class, 'create'])->name('add.purchasing-req');
    Route::post('/store/purchasing-req', [App\Http\Controllers\PurchasingreqController::class, 'store'])->name('store.purchasing-req');
    Route::get('/edit/purchasing-req/{id}', [App\Http\Controllers\PurchasingreqController::class, 'edit'])->name('edit.purchasing-req');
    Route::put('/update/purchasing-req/{id}', [App\Http\Controllers\PurchasingreqController::class, 'update'])->name('update.purchasing-req');
    Route::get('/delete/purchasing-req/{id}', [App\Http\Controllers\PurchasingreqController::class, 'delete'])->name('delete.purchasing-req');
    Route::get('/acc/purchasing-req/{id}', [App\Http\Controllers\PurchasingreqController::class, 'acc'])->name('acc.purchasing-req');
    Route::get('/decline/purchasing-req/{id}', [App\Http\Controllers\PurchasingreqController::class, 'decline'])->name('decline.purchasing-req');

    //incomes
     Route::get('/income', [App\Http\Controllers\IncomeController::class, 'index'])->name('income');
     Route::get('/add/income', [App\Http\Controllers\IncomeController::class, 'create'])->name('add.income');
     Route::post('/store/income', [App\Http\Controllers\IncomeController::class, 'store'])->name('store.income');
     Route::get('/edit/income/{id}', [App\Http\Controllers\IncomeController::class, 'edit'])->name('edit.income');
     Route::put('/update/income/{id}', [App\Http\Controllers\IncomeController::class, 'update'])->name('update.income');
     Route::get('/delete/income/{id}', [App\Http\Controllers\IncomeController::class, 'delete'])->name('delete.income');
     Route::get('/done/income/{id}', [App\Http\Controllers\IncomeController::class, 'done'])->name('done.income');
     Route::get('/on-progress/income/{id}', [App\Http\Controllers\IncomeController::class, 'on_progress'])->name('on-progress.income');

     //reimbursment progress
     Route::get('/Reimbursmentprog', [App\Http\Controllers\ReimbursmentprogController::class, 'index'])->name('Reimbursmentprog');
     Route::get('/add/Reimbursmentprog', [App\Http\Controllers\ReimbursmentprogController::class, 'create'])->name('add.Reimbursmentprog');
     Route::post('/store/Reimbursmentprog', [App\Http\Controllers\ReimbursmentprogController::class, 'store'])->name('store.Reimbursmentprog');
     Route::get('/edit/Reimbursmentprog/{id}', [App\Http\Controllers\ReimbursmentprogController::class, 'edit'])->name('edit.Reimbursmentprog');
     Route::put('/update/Reimbursmentprog/{id}', [App\Http\Controllers\ReimbursmentprogController::class, 'update'])->name('update.Reimbursmentprog');
     Route::get('/delete/Reimbursmentprog/{id}', [App\Http\Controllers\ReimbursmentprogController::class, 'delete'])->name('delete.Reimbursmentprog');
     Route::get('/done/Reimbursmentprog/{id}', [App\Http\Controllers\ReimbursmentprogController::class, 'done'])->name('done.Reimbursmentprog');
     Route::get('/on-progress/Reimbursmentprog/{id}', [App\Http\Controllers\ReimbursmentprogController::class, 'on_progress'])->name('on-progress.Reimbursmentprog');

    //cooperation
    Route::get('/Cooperation', [App\Http\Controllers\CooperationController::class, 'index'])->name('Cooperation');
    Route::get('/add/Cooperation', [App\Http\Controllers\CooperationController::class, 'create'])->name('add.Cooperation');
    Route::post('/store/Cooperation', [App\Http\Controllers\CooperationController::class, 'store'])->name('store.Cooperation');
    Route::get('/edit/Cooperation/{id}', [App\Http\Controllers\CooperationController::class, 'edit'])->name('edit.Cooperation');
    Route::put('/update/Cooperation/{id}', [App\Http\Controllers\CooperationController::class, 'update'])->name('update.Cooperation');
    Route::get('/delete/Cooperation/{id}', [App\Http\Controllers\CooperationController::class, 'delete'])->name('delete.Cooperation');
    Route::get('/done/Cooperation/{id}', [App\Http\Controllers\CooperationController::class, 'done'])->name('done.Cooperation');
    Route::get('/on-progress/Cooperation/{id}', [App\Http\Controllers\CooperationController::class, 'on_progress'])->name('on-progress.Cooperation');

     //Propertyloan
     Route::get('/Propertyloan', [App\Http\Controllers\PropertyloanController::class, 'index'])->name('Propertyloan');
     Route::get('/add/Propertyloan', [App\Http\Controllers\PropertyloanController::class, 'create'])->name('add.Propertyloan');

resources/views/admin/poster/index.blade.php
@extends('layouts.app')

@section('title')
Manage Poster dan Information Update
@endsection

@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">
@endsection

@section('content')
  <section class="section">
      <div class="section-header">
          <h3 class="page__heading">Manage Poster dan Information Update</h3>
      </div>
      <div class="section-body">
              <div class="card">
                <div class="card-header">
                  <a data-toggle="modal" data-target="#addPoster" class="btn btn-icon icon-left btn-primary" data-keyboard="false" data-backdrop="false"><i class="fas fa-user-plus"></i> Add Data</a>
         
                </div>
                <div class="card-body">
                  <div class="table-responsive table">
                    <table class="table table-striped" id="table-1">
                        <thead>
                            <tr>
                                <th style="width: 10%">#</th>
                                @if(Auth::user()->level == 0 || Auth::user()->level == 2)
                                <th>Poster</th>
                                @endif
                                <th>Aksi</th>
                                @if(Auth::user()->level == 0 || Auth::user()->level == 2)
                                <th>Tgl Dibuat</th>
                                <th>Tgl Diupdate</th>
                                @endif
                            </tr>
                        </thead>
                    <tbody>
                      @foreach ($data as $a)
                      <tr>
                        <td>
                          {{$loop->iteration}}
                        </td>
                        @if(Auth::user()->level == 0 || Auth::user()->level == 2)
                        <td>
                            
                            <a class="btn btn-dark" data-toggle="modal" data-target="#bukti{{$a->id}}" data-keyboard="false" data-backdrop="false">Lihat Poster</a>
                          
                        </td>
                        @endif

                        <td>
                          <a class="btn btn-icon icon-left btn-warning" data-toggle="modal" data-target="#edit{{$a->id}}"><i class="fas fa-pen-alt"></i> Edit Data</a>
                         
                          <a class="btn btn-icon icon-left btn-danger" onclick="return confirm('Yakin ingin menghapus data?')" href="{{route('admin.delete.poster', ['id' => $a->id])}}"><i class="fas fa-trash"></i> Hapus Data</a>
                        </td>
                        @if(Auth::user()->level == 0 || Auth::user()->level == 2)
                        <td>
                          {{date('d M Y H:m', strtotime($a->created_at))}}
                         </td>
                         <td>
                           {{date('d M Y H:m ', strtotime($a->updated_at))}}
                        </td>
                        @endif
                      </tr>
                      <div id="edit{{$a->id}}" class="modal fade" role="dialog" data-keyboard="false" data-backdrop="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Update Poster</h5>
                                    <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
                                </div>
                                <form method="POST" action="{{route('admin.update.poster', ['id' => $a->id])}}" enctype="multipart/form-data">
                                <div class="modal-body">
                                    @csrf
                                    {{method_field('PUT')}}
                                    <div class="section-title mt-0"><text>Poster Sebelumnya </text></div>
                                    <img src="{{asset($a->gambar)}}" width="100%">
                                    <div class="form-group">
                                        <label>Poster :</label>
                                        <input type="file" class="form-control" name="gambar" placeholder="Poster" aria-label="Poster">
                                        {{-- <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text" id="basic-addon1">@</span>
                                            </div>
    
                                        </div> --}}
                                    </div>
                                    <div class="text-right">
                                        <button type="submit" class="btn btn-primary btn-lg" id="btnPoster" data-loading-text="<span class='spinner-border spinner-border-sm'></span> Processing...">Save</button>
                                        <button type="button" class="btn btn-light ml-1" data-dismiss="modal">Cancel
                                        </button>
                                    </div>
                                </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    {{-- endmodal                 --}}

                    <div class="modal fade" id="bukti{{$a->id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="false">
                        <div class="modal-dialog bg-white">
                        <div class="modal-content bg-white">
                           <div class="modal-header">
                           <h5 class="modal-title" id="exampleModalLabel">Detail Poster</h5>
                           <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                     
                           </button>
                           </div>
                           <div class="modal-body">
                              <img src="{{ asset($a->gambar) }}" width = "100%">
                           </div>
                           <div class="modal-footer">
                           <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                           {{-- <a href="/user/profile/edit" class="btn btn-primary">Edit Profil</a> --}}
                           </div>
                        </div>
                        </div>
                     </div>
                      @endforeach
                      
                    </tbody>
                  </table>
                  </div>
                </div>
              </div>
      </div>
      <div id="addPoster" class="modal fade" role="dialog" data-keyboard="false" data-backdrop="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Tambahkan Poster</h5>
                    <button type="button" aria-label="Close" class="close" data-dismiss="modal">×</button>
                </div>
                <form method="POST" id='formPoster' action="{{route('admin.store.poster')}}" enctype="multipart/form-data">
                <div class="modal-body">
                    @csrf
                    <div class="form-group">
                        <label>Poster :</label>
                        <input type="file" class="form-control" name="gambar" placeholder="Poster" aria-label="Poster">
                        {{-- <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="basic-addon1">@</span>
                            </div>

                        </div> --}}
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary btn-lg" id="btnPoster" data-loading-text="<span class='spinner-border spinner-border-sm'></span> Processing...">Save</button>
                        <button type="button" class="btn btn-light ml-1" data-dismiss="modal">Cancel
                        </button>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
    {{-- endmodal                 --}}
    </section>
    
@endsection

@section('scripts')

<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>
<script>
    $(document).ready(function() {
        $('#table-1').DataTable();
    })
</script>

@endsection